In [5]:
#from array import *
a=array('i',[1,2,3,4,5])
print(a)

array('i', [1, 2, 3, 4, 5])


In [13]:
from numpy import *
b=linspace(0,20,5)
print(b)

[ 0.  5. 10. 15. 20.]


In [19]:
#from numpy import *
d=arange(0,22,3)
print(d)

[ 0  3  6  9 12 15 18 21]


In [21]:
c=logspace(0,22,10)
print(c)

[1.00000000e+00 2.78255940e+02 7.74263683e+04 2.15443469e+07
 5.99484250e+09 1.66810054e+12 4.64158883e+14 1.29154967e+17
 3.59381366e+19 1.00000000e+22]


In [22]:
e=zeros(4)
e

array([0., 0., 0., 0.])

In [24]:
f=ones(6, int)
f

array([1, 1, 1, 1, 1, 1])

In [29]:
a=array(range(5))
a

array([0, 1, 2, 3, 4])

In [27]:
a= a+2
a

array([2, 3, 4, 5, 6, 7])

In [35]:
c= a+b
print(a)
print(b)
print(c)
print(sin(c))
print(cos(c))
print(sum(c))
print(min(c))
print(max(c))
print(sort(c))

[0 1 2 3 4]
[ 0.  5. 10. 15. 20.]
[ 0.  6. 12. 18. 24.]
[ 0.         -0.2794155  -0.53657292 -0.75098725 -0.90557836]
[1.         0.96017029 0.84385396 0.66031671 0.42417901]
60.0
0.0
24.0
[ 0.  6. 12. 18. 24.]


In [37]:
concatenate([a,b])

array([ 0.,  1.,  2.,  3.,  4.,  0.,  5., 10., 15., 20.])

In [39]:
a=b.view()
print(id(a))
print(id(b))

1387440646544
1387440553872


In [40]:
a

array([ 0.,  5., 10., 15., 20.])

In [42]:
c=concatenate([a,b])

In [43]:
c

array([ 0.,  5., 10., 15., 20.,  0.,  5., 10., 15., 20.])

In [45]:
c.size

10

In [91]:
from array import *
print(c.shape)
c.size
c=c.flatten()
a
#c=a+c
c#.size

#print(c)

(10,)


array([ 0,  5, 10, 15, 20,  0,  5, 10, 15, 20])

In [98]:
c= concatenate([a,c])
c
c.size

30

In [102]:
d=c.reshape(5,2,3)
print(d)

[[[ 0.  5. 10.]
  [15. 20.  0.]]

 [[ 5. 10. 15.]
  [20.  0.  5.]]

 [[10. 15. 20.]
  [ 0.  5. 10.]]

 [[15. 20.  0.]
  [ 5. 10. 15.]]

 [[20.  0.  5.]
  [10. 15. 20.]]]
